development:
  adapter: mysql2
  database: crufree
  username: crufree
  host: localhost
  port: 3306

production:
  adapter: mysql2
  database: <%= ENV['DB_HOSTNAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
